# Generated by Django 5.1.7 on 2025-03-26 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0003_result_math_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='math',
            options={'ordering': ['-id']},
        ),
    ]
